hidden_dim: 256
output_dim: 60
batch_size: 32
input_dim: 60
train_split: 0.8
num_steps: 1000000
print_steps: 10000
learning_rate: 0.0002
lengths:
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 14
  - 16
  - 18
  - 20
