model_names:
  - "Transformer"
  - "Mamba"
  - "RNN"
  - "S4"
lengths:
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 14
  - 16
  - 18
  - 20
depths:
  - 1
  - 2
  - 3
  - 4
input_dim: 60
output_dim: 60
hidden_dim: 1024
state_dim: 64
batch_size: 32
learning_rate: 0.0002
num_epochs: 40
