runs: 5
model_names:
  - "S4"
  - "Mamba"
input_dims:
  - 2
  - 3
depth_nonlinears:
  - [2, True]
  - [2, False]
  - [1, False]
output_dim: 1
hidden_dim: 256
state_dim: 256
batch_size: 32
learning_rate: 0.0001
num_epochs: 401
